#!/bin/bash

# Get the directory where the current script is located
SCRIPT_PATH=$(dirname "$0")

RTF_SOURCE_PATH="${SCRIPT_PATH}"
OLD_PYTHONPATH=$PYTHONPATH
export PYTHONPATH=${RTF_SOURCE_PATH}:${OLD_PYTHONPATH}
python3 "${RTF_SOURCE_PATH}"/cli/app.py "$@"
